import Head from "next/head";

import { useEffect, useState } from "react";

import Filter from "@/components/filter"
import ViewData from "@/components/viewData";

import { Employee } from "@prisma/client";

export default function Home() {

  const [data, setData] = useState<Employee[] | undefined>(undefined)

  useEffect(() => {
    fetch('/api/getSheet')
      .then(r => r.json())
      .then((r: Employee[]) => setData(r))
      .catch(err => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Organization Charter - Improved</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-black">
        <Filter/>
        <ViewData data={data}/>
      </main>
    </>
  );
}