import Head from "next/head";

import { createContext, useEffect, useState } from "react";

import Filter from "@/components/filter"
import ViewData from "@/components/viewData";

import type { Filter as Filters } from "@/types/common/filters";

type filterContextType = {
    filters: Filters,
    setFilters: React.Dispatch<React.SetStateAction<Filters>> | undefined
}

const initialFilter: Filters = {
    name: "",
    functionalLead: "",
    teamName: "",
    teamLead: "",
    domain: "",
    domainLead: "",
    tribe: "",
    tribeLead: "",
    tribeArea: "",
    tribeAreaLead: ""
}

export const filterContext = createContext<filterContextType>({
  filters: initialFilter,
  setFilters: undefined
});

export default function Home() {

  const [filters, setFilters] = useState<Filters>(initialFilter);

  return (
    <>
      <Head>
        <title>Organization Charter - Improved</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <filterContext.Provider value={{
          filters: filters,
          setFilters: setFilters
        }}>
          <Filter/>
          <ViewData/>
        </filterContext.Provider>
      </main>
    </>
  );
}